apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference
        image:  gcr.io/int3319-477808/inference:v3
        imagePullPolicy: Always
        env:
          - name: TOPIC_ID
            value: "prediction-alerts"
          - name: SUBSCRIPTION_ID
            value: "inference_sub"
        resources:
          requests:
            cpu: 1000m
            memory: "1Gi"
          limits:
            cpu: 1000m
            memory: "1Gi"
      serviceAccountName: inference-pod-sa
      nodeSelector:
        cloud.google.com/compute-class: 'Performance'


